publishdir = "public"
static = "/static"
builddrafts = false
# Replace this with your website URL
baseurl = ""
canonifyurls = true
theme = "hugo-academic-group"
title = "Center for Health Innovation, Research, Action and Learning - Bangladesh (CHIRAL Bangladesh)"
math = true
copyright = "&copy; Center for Health Innovation, Research, Action and Learning - Bangladesh"
enableRobotsTXT = true

[taxonomies]
category = "categories"
tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "The Center for Health Innovation, Research, Action and Learning - Bangladesh (CHIRAL Bangladesh) is a non-profit health research organization in Bangladesh"
  author = "CHIRAL Bangladesh"
  email = "chiralbd@gmail.com"
  #youtube = "https://www.youtube.com/channel/UCAcwD0rF2Rm-sp1c2LUWh4w"
  address = '<a>Azimpur, 7/7, Dhaka, Bangladesh</a>'
  slogan = "CHIRAL<b>BD</b>"
  slogan_icon = "icon-spsbrats_logo"
  slogan_text = "Better Insights, Better Lives"
  custom_css = ["biaslab.css"]
  landing_heading = "Better Insights, Better Lives"
  landing_description = "The Center for Health Innovation, Research, Action and Learning - Bangladesh (CHIRAL Bangladesh) is a non-profit health research organization in Bangladesh"
  positions_available = true

  [params.logo]
    image = "img/chiralbd.png"
    link = "/"

  # [[params.navbar_hierarchy]]
  #   name = "SPS"
  #   link = "https://www.tue.nl/en/research/research-groups/signal-processing-systems/"
  #   position = 1
  #
  # [[params.navbar_hierarchy]]
  #   name = "Health Data Research Organization"
  #   link = "/"
  #   position = 2

  # [[params.sponsors]]
  #   name = "NWO"
  #   link = "http://www.stw.nl"
  #   image = "/img/sponsors/thals.png"
  #
  # [[params.sponsors]]
  #   name = "GN Resound"
  #   link = "http://www.resound.com/"
  #   image = "/img/sponsors/GNResound.png"



  # Selected Publications section.
  [params.publications_selected]
    detailed_list = false
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 5
    detailed_list = false
    title = "Working Papers"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    title = "News"
    subtitle = ""
    str_all = "More"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 5
    str_all = "More Projects"

  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.open_projects]
    title = "Open projects"
    subtitle = ""
    count = 3
    str_all = "All open projects"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
    name = "Home"
    url = "/#home"
    weight = 1
  [[menu.main]]
    name = "About CHIRAL"
    weight = 2
    identifier = "about"
  [[menu.main]]
    name = "About Us"
    url = "/about"
    parent = "about"
    weight = 1
  [[menu.main]]
    name = "Constitution"
    url = "/constitution"
    parent = "about"
    weight = 2

    [[menu.main]]
      name = "Collaboration and Authorship"
      url = "/collaboration-and-authorship"
      parent = "about"
      weight = 3

[[menu.main]]
    name = "Research"
    weight = 2
    identifier = "research"
  [[menu.main]]
    name = "Research Focus"
    weight = 1
    parent = "research"
[[menu.main]]
    name = "Projects"
    url = "/#projects"
    parent = "research"
    weight = 2
 [[menu.main]]
    name = "Publications"
    url = "/#publications"
    parent="research"
    weight = 3
  [[menu.main]]
    name = "News"
    url = "/#post"
    parent = "research"
    weight = 4

 [[menu.main]]
    name = "People"
    url = "/#members"
    weight = 5


 [[menu.main]]
    name = "Team"
    url = "chiralteam"
    weight = 5


  [[menu.main]]
    name = "Teaching"
    identifier = "teaching"
    weight = 6

  [[menu.main]]
    name = "Ongoing: Research ToolBox: A Step by Step Guide"
    url = "/teaching/research-toolbox/program-intro"
    parent = "teaching"
    weight = 1
    [[menu.main]]
    name = "All Programs: CHIRAL Training Modules"
    url = "/teaching/Programs"
    parent = "teaching"
    weight = 2
   [[menu.main]]
    [[menu.main]]
    name = "Program 1: Scientific Computing for Biologists"
    url = "/teaching/SCB"
    parent = "teaching"
    weight = 3
      [[menu.main]]
    [[menu.main]]
    name = "Program 2: Health Data Analytics"
    url = "/teaching/HDA"
    parent = "teaching"
    weight = 4



   [[menu.main]]
    name = "Resources"
    weight = 6
    url = "/resources"

  [[menu.main]]
    name = "Join"
    url = "#open-projects"
    weight = 7
    identifier="joinus"
  [[menu.main]]
    name = "Health Data Science Center(HDSC)"
    url = "/research/hdsc"
    parent="joinus"
    weight = 8

  [[menu.main]]
    name = "Genomic Data Science Center(GDSC)"
    url = "/research/gdsc"
    parent="joinus"
    weight = 8
  [[menu.main]]
    name = "Geospatial Health Research Lab(GHRL)"
    url = "/research/ghrl"
    parent="joinus"
    weight = 9

  [[menu.main]]
    name = "Research Assistant Confidentiality Agreement"
    url = "/research-assistant-confidentiality-agreement"
    parent="joinus"
    weight = 9

   [[menu.main]]
    name = "Starter's Guide for New Team Members"
    url = "/research/starter-guide"
    parent="joinus"
    weight = 10

  [[menu.main]]
    name = "Collaborators"
    url = "/collaborators"
    weight = 9

  # [[menu.main]]
  #   name = "Open projects"
  #   url = "/open-projects"
  #   parent = "joinus"

  [[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 9



  # [[menu.main]]
  #   name = "Software"
  #   weight = 3
  #   identifier = "software"

  # [[menu.main]]
  #   name = "ForneyLab.jl"
  #   url = "https://biaslab.github.io/ForneyLab.jl/stable/"
  #   parent = "software"
  #   weight = 1

  # [[menu.main]]
  #   name = "Rocket.jl"
  #   url = "https://biaslab.github.io/Rocket.jl/stable"
  #   parent = "software"
  #   weight = 2
